### ISSUE TITLE
perform optimization for all setting combinations

### ISSUE THREAD

**Issue by markushal** [agoenergy/ptx-boa#328]
- create script that iterates through all combinations
- perhaps start with all chains an RES types for a single country to check if everything is feasible
- check with @wingechr :
  - does hashing work
  - netcdf should also be exported
- check with @markushal which settings are relevant and which are not
-

**Comment by joAschauer** [comment]
Hi @markushal & @wingechr,
#336 is ready. I did not want to start it since #335 is still marked as draft and I did not know if things are going to change. At the top of the optimization script you find documentation on how to run it on the server. The code is already installed on the server but needs to be updated to use the changes from #335 and #336.

**Comment by markushal** [comment]
> Hi @markushal & @wingechr, #336 is ready. I did not want to start it since #335 is still marked as draft and I did not know if things are going to change. At the top of the optimization script you find documentation on how to run it on the server. The code is already installed on the server but needs to be updated to use the changes from #335 and #336.

@joAschauer thanks! @wingechr I would be great if we could test this tomorrow, as Jo is on vacation the next week. Do you think you can merge #335 into develop today or tomorrow?

**Comment by wingechr** [comment]
ok, all merged.

the offline optimization is currently running (`screen -r 19607`)
