### ISSUE TITLE
pre-commit ci

### ISSUE THREAD

**Issue by joAschauer** [agoenergy/ptx-boa#35]
Hi @RichChang963,

are you willing to install [pre-commit.ci](https://pre-commit.ci/) for this repository?

**Comment by RichChang963** [comment]
Hi @joAschauer,

Sure. This service is beneficial for the pre-commit workflow!

**Comment by joAschauer** [comment]
Hi @RichChang963, could you please give an update on this? Have you already attempted to install pre-commit.ci?

**Comment by RichChang963** [comment]
Hi @joAschauer ,

Sorry for late reply since I was in a business trip. I installed the pre-commit.ci into this repo, so it should be able to work now. Feel free to let me know if it is not working and I will have a look into it.

<img width="407" alt="image" src="https://github.com/agoenergy/ptx-boa/assets/13115072/94056e76-8677-40d8-849e-aaa375d5dff5">
